services:
  - type: web
    name: edulink-server
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push --accept-data-loss && npx ts-node prisma/seed.ts && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Pgbouncer URL (port 6543) + ?pgbouncer=true
      - key: DIRECT_URL
        sync: false # Direct URL (port 5432)
      - key: JWT_SECRET
        sync: false
